<a href="https://colab.research.google.com/github/yihan4326/MSSP607/blob/main/WeeklyModules/Week06/participation_week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import userdata
import os
import subprocess
import pandas as pd

# Go back to the main Colab directory
os.chdir('/content')

# Get GitHub token from Colab Secrets
github_token = userdata.get('Git_Key')

# Set the GitHub repository owner and name
owner = 'yihan4326'
repository = 'MSSP607'

# Create the clone URL
clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository if it does not already exist
if not os.path.exists(repository):
    subprocess.run(['git', 'clone', clone_url], check=True)

# Change directory to the repository
os.chdir(repository)

print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607

In [6]:
# Read the Student Performance Data Set
df = pd.read_csv('data/Student Performance Data.csv')

# Check the size of the data
print("Data shape:", df.shape)

# Display the first five rows
df.head()

Data shape: (1000, 10)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [7]:
# Create a lambda function to calculate the average score
new_df = (lambda data: data.assign(
    **{'average score': (data['math score'] + data['reading score'] + data['writing score']) / 3}
))(df)

# Display the new DataFrame
new_df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average score
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.666667
1,female,group C,some college,standard,69,90,88,247,completed,high,82.333333
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.666667
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,49.333333
4,male,group C,some college,standard,76,78,75,229,none,high,76.333333